### ISSUE TITLE
Stuck at Healthcheck on fresh install Ubuntu server on Oracle Cloud

### ISSUE THREAD

**Issue by dm5n** [standardnotes/self-hosted#96]
**Service Versions**

```
Container                             Repository                        Tag                 Image Id            Size
api-gateway-standalone                standardnotes/api-gateway         latest              a62067a708be        202MB
auth-standalone                       standardnotes/auth                latest              8d1eeb20557a        216MB
auth-worker-standalone                standardnotes/auth                latest              8d1eeb20557a        216MB
cache-standalone                      redis                             6.0-alpine          ddf87e4ac647        24.4MB
db-standalone                         mysql                             8                   4b61a400e877        550MB
files-standalone                      standardnotes/files               latest              07af9015366f        203MB
syncing-server-js-standalone          standardnotes/syncing-server-js   latest              5e394e15d18c        214MB
syncing-server-js-worker-standalone   standardnotes/syncing-server-js   latest              5e394e15d18c        214MB
workspace-standalone                  standardnotes/workspace           latest              5d32f0691615        213MB
workspace-worker-standalone           standardnotes/workspace           latest              5d32f0691615        213MB
```

**Problem**
Stuck at Healthcheck:

```
sudo curl http://localhost:3000/healthcheck
curl: (7) Failed to connect to localhost port 3000 after 0 ms: Connection refused
```

I've opened port 3000 to TCP traffic.

**Logs**

```
api-gateway-standalone               | auth:3000 is unavailable yet - waiting for it to start
api-gateway-standalone               | auth:3000 is unavailable yet - waiting for it to start
api-gateway-standalone               | auth:3000 is unavailable yet - waiting for it to start
api-gateway-standalone               | auth:3000 is unavailable yet - waiting for it to start
api-gateway-standalone               | auth:3000 is unavailable yet - waiting for it to start
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone               | auth (172.18.0.6:3000) open
api-gateway-standalone               | auth:3000 is up - executing command
api-gateway-standalone               | syncing-server-js (172.18.0.5:3000) open
api-gateway-standalone               | syncing-server-js:3000 is up - executing command
api-gateway-standalone               | Starting Web...
api-gateway-standalone               | files (172.18.0.4:3000) open
api-gateway-standalone               | files:3000 is up - executing command
api-gateway-standalone               | /workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23
api-gateway-standalone               |             throw new Error(`Environment variable ${key} not set`);
api-gateway-standalone               |                   ^
api-gateway-standalone               |
api-gateway-standalone               | Error: Environment variable REVISIONS_SERVER_URL not set
api-gateway-standalone               |     at Env.get (/workspace/packages/api-gateway/dist/src/Bootstrap/Env.js:23:19)
api-gateway-standalone               |     at ContainerConfigLoader.load (/workspace/packages/api-gateway/dist/src/Bootstrap/Container.js:49:82)
api-gateway-standalone               |     at Object.<anonymous> (/workspace/packages/api-gateway/dist/bin/server.js:33:16)
api-gateway-standalone               |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
api-gateway-standalone               |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
api-gateway-standalone               |     at require$$0.Module._extensions..js (/workspace/.pnp.cjs:12591:33)
api-gateway-standalone               |     at Module.load (node:internal/modules/cjs/loader:1037:32)
api-gateway-standalone               |     at require$$0.Module._load (/workspace/.pnp.cjs:12411:22)
api-gateway-standalone               |     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
api-gateway-standalone               |     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
api-gateway-standalone               |
api-gateway-standalone               | Node.js v18.12.1
api-gateway-standalone exited with code 1
```

**Comment by karolsojko** [comment]
Should be fixed now

**Comment by dm5n** [comment]
Confirming that it's fixed, thanks.

I had to cut and paste from the updated api-gateway.env file to the api.gateway.env.sample file due to line mismatch error – what would be best practice?
